### ISSUE TITLE
undefined errors.Unwrap

### ISSUE THREAD

**Issue by AxelTheGerman** [hashicorp/go-retryablehttp#106]
Hi,
Not sure if this is an issue with `go-retryablehttp` but everything used to work fine. Now when I run our test script (without any code changes) when it gets to the Golang part I'm seeing this error:

```
# github.com/hashicorp/go-retryablehttp
/go/pkg/mod/github.com/hashicorp/go-retryablehttp@v0.6.7/roundtripper.go:48:16: undefined: errors.Unwrap
```

And I can see `0.6.7` was just tagged 5 hours ago - unfortunately I don't know how I can make it use 0.6.6 again to see if that solves the issue.
There is a `go.mod` file which has the content
```
module github.com/our-org/our-sdk-go

require (
	github.com/antihax/optional v1.0.0
	github.com/hashicorp/go-retryablehttp v0.6.7
	golang.org/x/oauth2 v0.0.0-20190402181905-9f3314589c9a
)
```
but when I modify it and run the script again it seems to get re-generated?

**Comment by ncabatoff** [comment]
Hi @AxelTheGerman ,

Sorry, that's my doing.  I'll have a look and see what I can do to fix this and generate a new release.  In the meantime, you should be able to fix your project using

```
go get github.com/hashicorp/go-retryablehttp@v0.6.6
```

**Comment by ncabatoff** [comment]
Oh, actually I don't think that is my doing.  The use of Unwrap was introduced in 7cf40fa96c3780d7388eab86d563148f9a209005, making this library now require Go 1.13.  I'm not sure if that was intentional, but the go.mod on this project has had `go 1.13` in it since last October.

**Comment by ncabatoff** [comment]
Filed #107 to update the readme with the new requirement.

**Comment by AxelTheGerman** [comment]
Okay thanks for looking into it. I'm sure I'll get it sorted out from here 👍

**Comment by AxelTheGerman** [comment]
Ah I didn't see that error message before, sorry not familiar with Go - we just generate SDKs for multiple languages

```
# github.com/hashicorp/go-retryablehttp
/go/pkg/mod/github.com/hashicorp/go-retryablehttp@v0.6.7/roundtripper.go:48:16: undefined: errors.Unwrap
note: module requires Go 1.13
Makefile:101: recipe for target 'go-build' failed
```

Updating our docker image to `golang:1.13` solved it 👍 thanks!
